### PR TITLE
A splash of orpheus✨

### PR DESCRIPTION
**Pull request by dinaelhanan**

### CODE REVIEW

**Comment by sampoder** [comment]
ooooohh i wanna try, do you have a repl.it preview link to try (vercel is picky with who can have deploy previews)

**Comment by dinaelhanan** [comment]
@sampoder yup!! you can see it here: https://summer-scrapbook-1--dinaelhanan.repl.co/

**Comment by lachlanjc** [comment]
Hey @dinaelhanan! Could you share some context on these changes & what you’re looking to do? Personally, I think an Orpheus icon on the profiles feels kind of out of place there since it’s not user-specific.

**Comment by dinaelhanan** [comment]
@lachlanjc for sure; I'm trying to raise awareness w new members about orpheus legion. this is really just a rough idea so if you think there's a better way to do this lmk.

**Comment by lachlanjc** [comment]
Ok, awesome. But how does this tie into Orpheus Legion? It's linking to a bio of Orpheus, which doesn't mention anything in that vain…I just feel like people will be confused why this is on everyone's profiles. I'm totally in support of promoting OL here, I just think this implementation is going to confuse more than promote.

We could totally add a field & check on the backend if you're in the OL channel & show a badge if so. What link could we use that would explain this to people? Do we want to make a page about OL on our site?

**Comment by lachlanjc** [comment]
I'm going to close for now since it's been stale & there are a number of merge conflicts, but feel free to re-open with new comnits if we can solve some of the problems above! Thanks 😊

**Pull request closed without merging**
