### PR TITLE
Add some gap between mention image and text

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by lachlanjc** [comment]
:) can you edit the CSS file instead? There's already selectors to customize these elements & inline styles make it way harder for folks to use custom CSS. (Also, avoid half pixels with whitespace.)

**Comment by sampoder** [comment]
i can do that

**Comment by lachlanjc** [comment]
Yay! This will add margin to other types of mentions like the vertical webrings, so let's move the line down into the `post-text-mention`

**Comment by sampoder** [comment]
why'd that break it

**Review by lachlanjc — APPROVED** [review]
Cute!!

**Pull request merged**
