### PR TITLE
Create a little thing at the bottom

### PR DESCRIPTION
**Pull request by sampoder**
A message of encouragement to get started

### CODE REVIEW

**Comment by sampoder** [comment]
oooohh it actually deployed interesting, why do styles always break on css previews let me find my glitch

**Comment by sampoder** [comment]
https://repl.it/@sampoder/summer-scrapbook

**Comment by sampoder** [comment]
https://summer-scrapbook--sampoder.repl.co/ next.js is super slow on repl it

**Comment by sampoder** [comment]
Screen Shot 2020-06-21 at 11 10 40 PM
Screen Shot 2020-06-21 at 11 10 23 PM

**Comment by lachlanjc** [comment]
Nice touch!

**Pull request merged**
