### PR TITLE
Add Formatting

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by sampoder** [comment]
Don't merge until: https://github.com/hackclub/scrappy/pull/26

**Comment by lachlanjc** [comment]
Hey! Really appreciate this, but after looking into security implications, going to stick to autolinking on the frontend.

**Comment by sampoder** [comment]
cool, ya this wasnt the most secure way

**Comment by lachlanjc** [comment]
Decided to keep this all on the frontend with #31

**Pull request closed without merging**
