### PR TITLE
Proper tooltip display with react-tooltip

### LINKED ISSUE #60: Tooltip showing amount of "posts" in the activity grid
image
When hovering over tiles where `posts-count >= 1`, a tooltip should appear showing the exact amount of posts. Somewhat like GH has, but without showing the date - that's not needed.

### PR DESCRIPTION
**Pull request by alchzh**
The `titleOnValue` property in `react-calendar-heatmap` only works with the third party bootstrap tooltip library since it sets a `title` attribute instead of the SVG standard `<title>` tag. In any case, it appears the preferred method to implement the tooltip is with `react-tooltip` and the `tooltipDataAttrs` method instead as seen in https://github.com/kevinsqi/react-calendar-heatmap/blob/master/demo/src/Demo.js

`react-tooltip` doesn't play nicely with server side rendering, so we use a next/dynamic import to disable SSR for the `ReactTooltip` component.

Fixes #60 for real.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Thanks for this!! Will review later.

**Comment by lachlanjc** [comment]
I’m on my iPhone but looks like this page is entirely blank: https://summer-streaks-git-fork-alchzh-proper-tooltips.hackclub.dev/caleb

I want to make sure we’re not breaking people’s custom CSS too much with any site changes

**Comment by alchzh** [comment]
Hmm, weird. I can't see any differences at all (Firefox 80, Windows 10) I'll try to figure out what's going on, but I don't see why it would break custom CSS?

**Comment by alchzh** [comment]
Yeah, I don't think the issues with caleb's page have to do with my PR. https://scrapbook.hackclub.com/caleb shows up blank on my iPad and iPhone (strange twist of fate, eh?)

**Comment by alchzh** [comment]
I suspect this is the culprit:

https://gist.github.com/cjdenio/05d70b36875472a87d665ddb6c25aa1b#file-scrapbook-styles-css-L305

**Comment by lachlanjc** [comment]
Ah you’re totally right, didn’t realize that. I’m going to merge this & can adjust if there are any complaints :+1:

**Pull request merged**
