### PR TITLE
Fix posts starting with colons & improve emoji parsing

### LINKED ISSUE #86: Posts that start with a : appear on the website as a parrot emoji
IMG_0422
From Jess Ding’s latest post.

IMG_0421
This doesn’t happen if I move the :000

### PR DESCRIPTION
**Pull request by lachlanjc**
Closes #86

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/\[username\]**](https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/[username]) | [**/\[username\]/mentions**](https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/[username]/mentions) |
|:-:|:-:|
|<a href="https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/[username]">Screenshot of /[username]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/2q8TYo0svow22AmIOfoc_3C8s9Q_.png">(view full size)</a> |<a href="https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/[username]/mentions">Screenshot of /[username]/mentions</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/bdyGr5avn7byUIE2GQU7ljIF5xk_.png">(view full size)</a> |



| [**/**](https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/) |
|:-:|
|<a href="https://summer-streaks-git-hc-154-fix-colon.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/tHS4qYBgypTvIU84UlmJ2uubkx0_.png">(view full size)</a> |







Commit 99ae61113396baad6101e6e9301f68852aa30b01 (https://summer-streaks-git-hc-154-fix-colon.hackclub.dev).

**Comment by alchzh** [comment]
Doesn't this just wipe all emoji if you split by them?

**Comment by lachlanjc** [comment]
Nope! We split by each element that needs custom rendering, but use the parens around it so the data is kept. Then it checks which kind of token it is using the ifs & returns the appropriate component.

image

That said, looks like this broke custom emoji but not regular ones. (Regular are converted on the backend.) Going to roll back until I can investigate next week.

By the way—I stumped myself & a bunch of people writing a regex to handle @usernames with everything Slack can use (including periods in them) but exclude punctuation at the end ('!,. namely). If you have any suggestions there, would love to hear them.

**Comment by alchzh** [comment]
I don't think this PR was the cause of the emoji thing. see #98 . Next 9.5 seems to be rewriting API calls w/ trailing slashes which then fail the redirect filter in vercel.json

**Comment by alchzh** [comment]
>By the way—I stumped myself & a bunch of people writing a regex to handle @usernames with everything Slack can use (including periods in them) but exclude punctuation at the end ('!,. namely). If you have any suggestions there, would love to hear them.

I talked with @MatthewStanciu about this a bit earlier but I think the solution here is on scrappy's end since the bot currently converts slack `<@id>` strings into `@scrapbookusername` where instead it should be doing `<@scrapbookusername>` instead. Unless that was already tried and doesn't work?

**Comment by lachlanjc** [comment]
Cool. So I actually managed to figure it out! Came up with a solution avoiding regex. Thanks for your help here.

**Pull request merged**
