### PR TITLE
Add CI (continuous integration)

### PR DESCRIPTION
**Pull request by Matt-Gleich**
👋  Hello! I added CI to automatically make sure the `yarn run build` passes and that all files are formatted with prettier. I also added badges to the README which won't render yet until this PR gets merged. Hopefully, this helps!

### CODE REVIEW

**Comment by sampoder** [comment]
Thank you! I'll let Lachlan review this, thank you 🎉

**Comment by Matt-Gleich** [comment]
@lachlanjc any plans to merge this? I am just cleaning out some of my forks. No rush!

**Comment by lachlanjc** [comment]
I am not, sorry. I sat on it for a little while but I realized this just isn’t a needed part of the workflow for how I work on these sites. I super appreciate your effort though, so I’m sorry to waste it :/

**Comment by Matt-Gleich** [comment]
Totally understand, don't worry about it!

**Pull request closed without merging**
