### PR TITLE
HC-216 It's time to go back to back to the future

### PR DESCRIPTION
**Pull request by sampoder**
because the heat maps can't live in the past

### CODE REVIEW

**Comment by sampoder** [comment]
ahhh oops

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/\[username\]**](https://summer-streaks-git-back-to-the-future.hackclub.dev/[username]) |
|:-:|
|<a href="https://summer-streaks-git-back-to-the-future.hackclub.dev/[username]">Screenshot of /[username]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/xHi4CkPqJeFKYzTh3WFEIKKYZzg_.png">(view full size)</a> |







Commit 43821eb38315a7a900550f28bd75fc60b6d20ce4 (https://summer-streaks-git-back-to-the-future.hackclub.dev).

**Comment by sampoder** [comment]
👀

**Comment by sampoder** [comment]
whooo!!

**Comment by lachlanjc** [comment]
Whoo indeed! Thanks for kickstarting this, I totally forgot about it! Also keep your eyes peeled 🎃

**Comment by sampoder** [comment]
omgggg halloween theme!!! I was legit thinking that earlier today

**Pull request merged**
