### PR TITLE
HC-142 Desummer-ize Scrapbook

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by sampoder** [comment]
actually this is done, @lachlanjc can you take a look for me? thank you!

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/404**](https://summer-streaks-git-sunset.hackclub.dev/404) | [**/\[username\]**](https://summer-streaks-git-sunset.hackclub.dev/[username]) |
|:-:|:-:|
|<a href="https://summer-streaks-git-sunset.hackclub.dev/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/UXXT6Ksi24bUmQX8hUXgVbJ9qHs_.png">(view full size)</a> |<a href="https://summer-streaks-git-sunset.hackclub.dev/[username]">Screenshot of /[username]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Bmz_V99oyzCyiRyejvNQga5QG8A_.png">(view full size)</a> |



| [**/\[username\]/mentions**](https://summer-streaks-git-sunset.hackclub.dev/[username]/mentions) | [**/about**](https://summer-streaks-git-sunset.hackclub.dev/about) |
|:-:|:-:|
|<a href="https://summer-streaks-git-sunset.hackclub.dev/[username]/mentions">Screenshot of /[username]/mentions</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/G08JsNYajoizN2Aa9dqGkWrdVjY_.png">(view full size)</a> |<a href="https://summer-streaks-git-sunset.hackclub.dev/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Z0s4CAtRTNNogY_IetOJ0NUcDYI_.png">(view full size)</a> |



| [**/**](https://summer-streaks-git-sunset.hackclub.dev/) | [**/r/\[emoji\]**](https://summer-streaks-git-sunset.hackclub.dev/r/[emoji]) |
|:-:|:-:|
|<a href="https://summer-streaks-git-sunset.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/u85eIRA5MzoQQ6BVQcBQpVMlKQY_.png">(view full size)</a> |<a href="https://summer-streaks-git-sunset.hackclub.dev/r/[emoji]">Screenshot of /r/[emoji]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_EuWaDV8FY_QxDyC9HfTaIfnAdI_.png">(view full size)</a> |



And 2 other routes:
- [**/api/summer-posts**](https://summer-streaks-git-sunset.hackclub.dev/api/summer-posts)
- [**/summer**](https://summer-streaks-git-sunset.hackclub.dev/summer)



Commit e3e07b410ac993e5d86723a43049d2de58c83d0f (https://summer-streaks-git-sunset.hackclub.dev).

**Comment by sampoder** [comment]
oof stop blind commitign

**Comment by lachlanjc** [comment]
A quick update. I super appreciate you doing this, & it will go live in the next 2-ish weeks, but I want to make some code changes to how this works & it hasn’t been a priority to sit down & implement them. Thanks for your work, & it will be a thing soon!

**Comment by sampoder** [comment]
ok, epic!

**Comment by sampoder** [comment]
we can use custom css!

**Comment by lachlanjc** [comment]
Thank you so much for taking the initiative here! Sorry it took so long. Now live at https://summer.hackclub.com/summer

**Pull request merged**
