### PR TITLE
Add slackURL to post card

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:



- [**/api/posts**](https://summer-streaks-git-add-slack-url.hackclub.dev/api/posts)



Commit 895dc8f835c66dd9872730041e8e5c4f03e6d5f6 (https://summer-streaks-git-add-slack-url.hackclub.dev).

**Comment by maxwofford** [comment]
See changes:
https://youtu.be/OjwU7ZgnS18

**Comment by sampoder** [comment]
@lachlanjc @maxwofford merge?

**Comment by lachlanjc** [comment]
Closing since Zach disliked this implementation & merge conflicts—can re-explore in the future

**Comment by sampoder** [comment]
it'd be very subtle but what if you could hover over the time and get a tooltip saying view original post.. just an idea

**Pull request closed without merging**
