### PR TITLE
Index page only shows users with custom CSS

### PR DESCRIPTION
**Pull request by maxwofford**
Please don't merge! just playing with this to see what it'd feel like

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:



- [**/api/users**](https://summer-streaks-git-css-experiment.hackclub.dev/api/users)



Commit f1c3dcaf07d23652b3260354713491cf8fe99ed4 (https://summer-streaks-git-css-experiment.hackclub.dev).

**Comment by lachlanjc** [comment]
Btw, would appreciate if you marked such PRs as drafts so we don’t accidentally merge :)

**Comment by maxwofford** [comment]
Do drafts get a preview build?

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Comment by lachlanjc** [comment]
Yup! Every time you push to a branch

**Comment by lachlanjc** [comment]
It’s summer-streaks-git-BRANCH.hackclub.dev, so you can also just silently push to a branch

**Pull request closed without merging**
