### PR TITLE
Add Mentions Page

### LINKED ISSUE #74: Idea: a mention page for the user

### PR DESCRIPTION
**Pull request by sampoder**
been working on this on and off today it isn't really working rn {EDIT IT IS NOW WORKING YIPPEEEE}

edit: fixes #74

### CODE REVIEW

**Comment by sampoder** [comment]
this is now basically done

**Comment by sampoder** [comment]
I think its ready also fixes #74

**Comment by lachlanjc** [comment]
Nice work! Will review & make some edits soon as I can.

**Comment by lachlanjc** [comment]
Merging this into a branch on our repo so I can work on it. For some reason you didn’t have write permissions to this repo, sorry! Please continue putting all changes in PRs but you can make them on internal branches now so things are smoother.

**Pull request merged**
