### PR TITLE
Add Vercel Redirect to Domains Page for Project

### PR DESCRIPTION
**Pull request by sampoder**
too lazy to explain rn

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:



- [**/api/vercel-deploy-finished**](https://summer-streaks-git-sampoder-patch-1.hackclub.dev/api/vercel-deploy-finished)



Commit 45e573b4545d69200e4847ca521c58111841387c (https://summer-streaks-git-sampoder-patch-1.hackclub.dev).

**Comment by lachlanjc** [comment]
This isn't valid syntax 🙂 also not sure what it's supposed to do 🙂

**Comment by sampoder** [comment]
yep i'd completely ignore it for the moment, it's super supposed to take 

https://summer-streaks-git-sampoder-patch-1.hackclub.dev/api/vercel-deploy-finished/?project-dashboard-url=https%3A%2F%2Fvercel.com%2Fsampoder%2Fmy-scrapbooke&deployment-dashboard-url=https%3A%2F%2Fvercel.com%2Fsampoder%2Fmy-scrapbooke%2Fe8696ds88&deployment-url=https%3A%2F%2Fmy-scrapbooke.vercel.app&repository-url=https%3A%2F%2Fgithub.com%2Fsampoder%2Fscrapbook-redirectefqR

and redirect to https://vercel.com/sampoder/my-scrapbooke/settings/domains

**Comment by sampoder** [comment]
it's working! check out http://hack.af/scrapbook-domain to see how I'm using this, closing this coz I don't really want it inculded in the codebase and will just use hack.af/vercel-domain-dashboard

**Pull request closed without merging**
