### PR TITLE
Add Styles By Indicator (first draft)

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by sampoder** [comment]
@qmogh

**Comment by sampoder** [comment]
oh and if this isn't obvious ummm it won't be name there that's just a placeholder

**Comment by lachlanjc** [comment]
This will break on mobile, especially iPhone SE. Let's move to where Explore Reactions is?

**Comment by sampoder** [comment]
oof, ya I'll do that tomorrow

**Comment by sampoder** [comment]
oof lesson learnt don't blind push

**Comment by sampoder** [comment]
wait but why isn't it showing logs?

**Comment by sampoder** [comment]
still 404ing :(((((

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/**](https://summer-streaks-git-add-styles-by-indicator.hackclub.dev/) |
|:-:|
|<a href="https://summer-streaks-git-add-styles-by-indicator.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/waobT5e7U447sIjoozHjbyg8_uY_.png">(view full size)</a> |







Commit 95430c3235a86eef9e3bfe7ee16d8d8e53ec61c7 (https://summer-streaks-git-add-styles-by-indicator.hackclub.dev).

**Comment by sampoder** [comment]
OOOOOOHGHHHHH IT WORKEDD HACK YEAAHHH

**Pull request closed without merging**
