### PR TITLE
Foundations for the Octocat Contest

### PR DESCRIPTION
**Pull request by sampoder**
The Octocat contest starts tomorrow at noon, we aren't going to have enough time to create the categories thing, this allows us to have a basic thing that will get the job done

### CODE REVIEW

**Comment by sampoder** [comment]
really sorry to bug you Lachlan, but we're kinda announcing this in 40 minutes. I'm super sorry this was rushed

**Comment by lachlanjc** [comment]
I’m going to hold off here while we figure out the details of the event, happy to review later

**Comment by sampoder** [comment]
Ya Chris just told me

**Comment by sampoder** [comment]
closing coz #37 is a better solution by far

**Pull request closed without merging**
