### PR TITLE
Create a public playback ID when creating asset

### PR DESCRIPTION
**Pull request by dylanjha**
* Make 1 API call to Mux instead of 2

### CODE REVIEW

**Comment by dylanjha** [comment]
I couldn't find an easy to test this. Looks like I would have to craft some kind of slack request with the right parameters to hit `/api/slack/processMessage`. Someone should make sure this works *just to be sure*

**Comment by lachlanjc** [comment]
Thanks! So we actually are using hackclub/scrappy for this now, just never removed the code here. @maxwofford want to transfer & review?

**Comment by dylanjha** [comment]
@lachlanjc ah cool. The github icon in the nav on https://scrapbook.hackclub.com/ still points to this repo

**Comment by lachlanjc** [comment]
Yep! This repo is the website; just the Slack integration is the other repo.

**Comment by maxwofford** [comment]
This looks awesome! @MatthewStanciu built out the Mux integration, will leave for his review + transfer

**Comment by dylanjha** [comment]
closing this one, opened in hackclub/scrappy instead as suggested by @lachlanjc : https://github.com/hackclub/scrappy/pull/13

**Pull request closed without merging**
