### PR TITLE
Remove Leaderboard Site (Relocating)

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by sampoder** [comment]
Is there a way to make it so that the deploys work? Would be great to test it

**Comment by lachlanjc** [comment]
Sorry for the hassle…asked the Vercel team & sounds like no:

image

You could build this in a CodePen though right, since it’s just static?

**Comment by sampoder** [comment]
ya i made in glitch

**Comment by sampoder** [comment]
actually i can just make a redirect to glitch in the file

**Comment by sampoder** [comment]
My new plan is to relocate to a separate domain: https://github.com/hackclub/dns/pull/309

**Pull request merged**
